### ISSUE TITLE
Problem with vecpair2rmat

### ISSUE THREAD

**Issue by oliverkjohnson** [sgbaird-5DOF/interp#27]
In `vecpair2rmat` if the two vectors are antipodal to within a certain tolerance, the inversion, $-I$, is returned. This isn't a bug, as it was clearly intentional, but it does have undesirable consequences. In particular, $-I$ is an improper rotation, so when it is supplied to `om2qu` the result is a quaternion that has complex values, which subsequent functions choke on. Since the result of `vecpair2rmat` is non-unique, I suggest that a better default behavior for antipodal vectors is to return a rotation of $\pi$ about an axis that is orthogonal to the vectors. This will be a proper rotation, so it won't cause subsequent functions to choke.

**Comment by oliverkjohnson** [comment]
Nevermind, I think I found it (`ax2om`). This works:
`    null_space = null(v1); % arbitrary basis for the null space of v1.'
    vAx = null_space(:,1); % choose one of the basis vectors as the rotation axis
    R = ax2om([vAx(:).', pi]);`

**Comment by oliverkjohnson** [comment]
Just as an aside, this choice becomes important to handle the centrosymmetric point groups because we have to enforce `[qm,nA]~[qm,-nA]`, which amounts to including both in the list of symmetric octonions, and somewhere there is `vectpair2rmat(nA,-nA,1)` so we have to deal with the antipodal case carefully to make sure we stick with proper rotations, instead of improper ones.

**Comment by sgbaird** [comment]
> Nevermind, I think I found it (`ax2om`). This works:
> `null_space = null(v1); % arbitrary basis for the null space of v1.`
> `vAx = null_space(:,1); % choose one of the basis vectors as the rotation axis`
> `R = ax2om([vAx(:).', pi]);`

That's great. This will be a good fix to incorporate in the repository.



> Just as an aside, this choice becomes important to handle the centrosymmetric point groups because we have to enforce `[qm,nA]~[qm,-nA]`, which amounts to including both in the list of symmetric octonions, and somewhere there is `vectpair2rmat(nA,-nA,1)` so we have to deal with the antipodal case carefully to make sure we stick with proper rotations, instead of improper ones.

Good context.
