### ISSUE TITLE
Why is uniqueQ == false?

### ISSUE THREAD

**Issue by oliverkjohnson** [sgbaird-5DOF/interp#28]
I'm wondering why `uniqueQ` is set to false everywhere in the code (in particular inside `GBdist4`, which propagates to `osymsets` and eventually `osymset`)? It seems that if there are duplicates, they have no functional purpose and only require extra computations if they are preserved. Perhaps I'm missing something though?

**Comment by sgbaird** [comment]
IIRC, I used `uniqueQ==true` initially but found that the lists of octonions were already unique, and so it was to avoid extra computation running `uniquetol()` each time `osymset.m` was called, but maybe it wouldn't have affected the runtime. Setting to `true` should be fine, too, and maybe result in a speed-up if you're using lots of symmetric GBs.

https://github.com/sgbaird-5DOF/interp/blob/05c37ae2bc2388445fa35bde91876f7d7e633ac6/code/osymset.m#L87-L89
