### ISSUE TITLE
Why normr(o) before proj_down(o)?

### ISSUE THREAD

**Issue by oliverkjohnson** [sgbaird-5DOF/interp#32]
Hi Sterling,

Currently in `interp5DOF.m` you have
```
projQ = true;
zeroQ = false;
o = normr(o);
o2 = normr(o2);
[a,usv] = proj_down([o;o2],projtol,'zero',zeroQ,'force',nforceQ,'nforcedim',nforce);
```

Why do you normalize the octonions to unit length before doing the SVD projection? Is this necessary?

**Comment by sgbaird** [comment]
Necessary evil of compatibility with some of the other methods like spherical barycentric interpolation (at least in the current form) IIRC
